### ISSUE TITLE
read시 rdata질문

### ISSUE THREAD

**Issue by kkkod1150** [ECE4278/lab_answer#1]
안녕하세요
정답코드 관련해서 질문이 있습니다.
95~97번줄에 rdata에 drive되는 신호들이 src_addr, dst_addr, byte_len인데 src_addr_o, dst_addr_o, byte_len_o을 rdata에 drive하는 것이 맞는 것 아닌가 해서 질문드립니다. 만약 정답 코드가 맞는 정답이라면  src_addr_o, dst_addr_o, byte_len_o 해당 output들의 역할에 대하여 알 수 있을까요?

**Comment by dale40** [comment]
안녕하세요,

두가지 방법 모두 정상 동작합니다. 즉 rdata에 src_addr을 넣어도 되고 src_addr_o를 넣어도 되는데, 이는 assign src_addr_o = src_addr (line 109)으로 두 신호들이 같은 값을 갖기 때문입니다.

src_addr_o와 src_addr이 같은 값인데도 불구하고 별개의 신호로 선언된 이유는, 현재 coding style에서 모든 output 포트들이 _o의 suffix를 갖고 있고, 내부 신호들은 _o가 없어야 하기 때문에, 이들을 별개의 신호들로 선언해 준 다음에 이를 assign을 통해서 같은 신호로 만들어 줍니다.
